CREATE TABLE "role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "libelle" varchar
);

CREATE TABLE "utilisateur" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar,
  "mot_de_passe" varchar,
  "nom" varchar,
  "prenom" varchar,
  "telephone" varchar,
  "adresse_postale" varchar,
  "actif" boolean,
  "created_at" timestamp,
  "role_id" int
);

CREATE TABLE "theme" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "libelle" varchar
);

CREATE TABLE "regime" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "libelle" varchar
);

CREATE TABLE "allergene" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "libelle" varchar
);

CREATE TABLE "type_plat" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "libelle" varchar
);

CREATE TABLE "menu" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" varchar,
  "description" text,
  "nombre_personnes_min" int,
  "prix_base" decimal,
  "conditions" text,
  "stock_disponible" int,
  "actif" boolean,
  "theme_id" int,
  "regime_id" int
);

CREATE TABLE "image_menu" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar,
  "ordre" int,
  "menu_id" int
);

CREATE TABLE "plat" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar,
  "photo" varchar,
  "type_plat_id" int
);

CREATE TABLE "menu_plat" (
  "menu_id" int,
  "plat_id" int,
  PRIMARY KEY ("menu_id", "plat_id")
);

CREATE TABLE "plat_allergene" (
  "plat_id" int,
  "allergene_id" int,
  PRIMARY KEY ("plat_id", "allergene_id")
);

CREATE TABLE "horaire" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jour" varchar,
  "heure_ouverture" varchar,
  "heure_fermeture" varchar,
  "ferme" boolean
);

CREATE TABLE "commande" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date_prestation" date,
  "heure_livraison" time,
  "adresse_livraison" varchar,
  "nombre_personnes" int,
  "prix_menu" decimal,
  "prix_livraison" decimal,
  "prix_total" decimal,
  "statut" varchar,
  "motif_annulation" text,
  "mode_contact" varchar,
  "pret_materiel" boolean,
  "created_at" timestamp,
  "utilisateur_id" int,
  "menu_id" int
);

CREATE TABLE "historique_statut" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "statut" varchar,
  "date_changement" timestamp,
  "commande_id" int,
  "modifie_par" int
);

CREATE TABLE "avis" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" int,
  "commentaire" varchar,
  "statut" varchar,
  "created_at" timestamp,
  "commande_id" int,
  "utilisateur_id" int
);

CREATE TABLE "contact" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar,
  "titre" varchar,
  "message" text,
  "created_at" timestamp
);

ALTER TABLE "utilisateur" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu" ADD FOREIGN KEY ("theme_id") REFERENCES "theme" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu" ADD FOREIGN KEY ("regime_id") REFERENCES "regime" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "image_menu" ADD FOREIGN KEY ("menu_id") REFERENCES "menu" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plat" ADD FOREIGN KEY ("type_plat_id") REFERENCES "type_plat" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_plat" ADD FOREIGN KEY ("menu_id") REFERENCES "menu" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "menu_plat" ADD FOREIGN KEY ("plat_id") REFERENCES "plat" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plat_allergene" ADD FOREIGN KEY ("plat_id") REFERENCES "plat" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plat_allergene" ADD FOREIGN KEY ("allergene_id") REFERENCES "allergene" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "commande" ADD FOREIGN KEY ("utilisateur_id") REFERENCES "utilisateur" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "commande" ADD FOREIGN KEY ("menu_id") REFERENCES "menu" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "historique_statut" ADD FOREIGN KEY ("commande_id") REFERENCES "commande" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "historique_statut" ADD FOREIGN KEY ("modifie_par") REFERENCES "utilisateur" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avis" ADD FOREIGN KEY ("commande_id") REFERENCES "commande" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "avis" ADD FOREIGN KEY ("utilisateur_id") REFERENCES "utilisateur" ("id") DEFERRABLE INITIALLY IMMEDIATE;
